### ISSUE TITLE
amoled v2 screen not working with this fw

### ISSUE THREAD

**Issue by asg02fever** [roblatour/youtubescribercounter#1]

**Comment by roblatour** [comment]
That's odd.  Are you running it on battery or plugged into to USB?

Also, I've left a post on Lilygo community forum to ask about this:
https://community.lilygo.cc/topic/979/t-display-s3-amloled-v2-display-not-working-but-works-on-v1

Thanks for reporting it.

**Comment by asg02fever** [comment]
hello rob,
i am actually on the v2 i got it for free for a video collab are you
working on an update ?

your dear friend from france
morgan ledean

**Comment by roblatour** [comment]
@asg02fever as mentioned above I've left a post on Lilygo community forum to find out what I can.   I have since also opened a similar question within LilyGo's Github issue page: https://github.com/Xinyuan-LilyGO/LilyGo-AMOLED-Series/issues/41


I don't have a v2 board myself, so the best I can do is gather some info that would help solve the problem in theory.

Having that said, it may be something simple - like using another TFT_eSPI libary.

I have since updated my webpage to note the program works on v1 of the board but not v2.

By the way, what happened to your original post where you said the display was not working - the post seems to have been removed??   

Also, as above, are you running it on battery or plugged into to USB?

**Comment by asg02fever** [comment]
hi rob

 i did not do anything to the post i may have been deleted automatically
i am running on usb atm i am trying to find a small lit ion battery that
would fin this build and some others

if u have the information to what code i need to change to make it work on
the v2 hit me up also if u are interested i have an affiliate link no
cuppon for the moment but i gain small commission
i am a content creator @keebasg on tiktok and youtube

regards.
morgan ledean

**Comment by roblatour** [comment]
@asg02fever 

Can you please try making the following change:

In  the file YouTubeSubscriberCounter.ino 

change the code that currently reads:

```
void ToogleGreenLed(bool toggleOn) {

  if (toggleOn) {t
    digitalWrite(led, HIGH);
  } else {
    digitalWrite(led, LOW);
  }
}
```

to 

```
void ToogleGreenLed(bool toggleOn) {

    digitalWrite(led, HIGH);

}
```


Once done, please give it a test and let me know if it works (I would test it myself but I don't have v2 of the board to test with).

Of note, if this works for you, I will update the code in a better way - but what I am being told is that effectively v1 of the board uses IO Pin 38 for the green led, and v2 for the backlight.  If true, the above change will make it work for your use of v2 of the board.

**Comment by roblatour** [comment]
@asg02fever just following up ...

**Comment by asg02fever** [comment]
hey rob , sorry i havnt seen your message, would you like to add me on
discord for making it easier today ( its the lunch time there but ill be
free for you byt the end on the day )

discord keebasg

**Comment by roblatour** [comment]
No problem, you can e-mail me at info@rlatour.com if you like.  Really, just wondering if the fix above corrects it for you.  If it does I can work from there.

**Comment by asg02fever** [comment]
hey,

the fix didnt worked also i got some errors cause i had to make a fresh
install of windows and i lost all my libs thats why i wanted to do it in a
call screenshare with you to make it easier for both of us

**Comment by asg02fever** [comment]
hey,

the fix didnt worked also i got some errors cause i had to make a fresh
install of windows and i lost all my libs thats why i wanted to do it in a
call screenshare with you to make it easier for both of us
discord keebasg , or join my server https://discord.gg/JSTy7TwT

**Comment by lewisxhe** [comment]
I have replied [here](https://github.com/Xinyuan-LilyGO/LilyGo-AMOLED-Series/issues/41)

**Comment by roblatour** [comment]
The fix should be as described here:

https://github.com/Xinyuan-LilyGO/LilyGo-AMOLED-Series/issues/41#issuecomment-2159587325


please test it and if you can confirm it works for you I can update the library.

**Comment by roblatour** [comment]
Thanks for confirming the fix worked.  

I've updated the code so it will support both versions of the board; for this there is a new setting in the file general_settings.h as follows:

`#define GENERAL_SETTINGS_AMOLED_VERSION  1  // set to 1 if you are using the Lilygo T-Display S3 AMOLED v1`
`                     // set to 2 if you are using the Lilygo T-Display S3 AMOLED v2`
`                     // for more information please see: https://www.lilygo.cc/en-ca/products/t-display-s3-amoled`

Thanks for reporting the issue now resolved
